# fly.toml app configuration file generated for rstpblog on 2023-05-08T10:03:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rstpblog"
primary_region = "eze"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
